def input_error(func):
    def inner(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except KeyError as e:
            return e
        except ValueError as e:
            return e
        except Exception as e:
            return "An unexpected error occurred. Please try again."

    return inner
